### ISSUE TITLE
Need check statement for file or dir exists before cp command

### ISSUE THREAD

**Issue by MeenachiSundaram** [jjlin/bitwardenrs-backup#1]
https://github.com/jjlin/bitwardenrs-backup/blob/main/backup.sh#L42

```
+ cp -a data/attachments data/config.json data/rsa_key.der data/rsa_key.pem data/rsa_key.pub.der ${HOME}/bitwarden/backup/bitwarden-20210221-0820
cp: cannot stat 'data/attachments': No such file or directory
```

**Comment by jjlin** [comment]
As mentioned in the README, this script is primarily for my use, not to fit anyone else's particular needs. I'm willing to make reasonable accommodations to make it a little more general, but people should feel free to make whatever changes they feel are necessary to their own copy.

I'll add a fix for this and push the changes assuming there are no issues in my next backup.
