### ISSUE TITLE
when script fails BACKUP_DIR_NAME created but not cleaned up

### ISSUE THREAD

**Issue by MeenachiSundaram** [jjlin/bitwardenrs-backup#2]
https://github.com/jjlin/bitwardenrs-backup/blob/main/backup.sh#L13

$ tree -L 1
.
├── LICENSE
├── README.md
├── archives
├── backup.conf
├── backup.conf.template
├── backup.sh
├── bitwarden-20210221-0820
└── crontab

2 directories, 6 files

**Comment by jjlin** [comment]
My backups aren't supposed to fail, so if they do, I'd rather see what the failed state was instead of deleting it.
